packages:
- skylighting-core
- skylighting
- skylighting-format-ansi
- skylighting-format-blaze-html
- skylighting-format-context
- skylighting-format-latex
- skylighting-format-typst
resolver: lts-23.3
ghc-options:
    "$locals": -Wall -optP-Wno-nonportable-include-path
